query GetBanners(
  $first: Int
  $offset: Int
  $filter: BannerFilter
  $sort: SortFilter
) {
  banners(first: $first, offset: $offset, filter: $filter, sort: $sort) {
    totalCount
    nodes {
      id
      image
      permalink
      position
    }
  }
}
