query getMyDeliveryRequests(
  $first: Int
  $after: String
  $sort: SortFilter = { field: "created_at", direction: desc }
) {
  me {
    id
    firstName
    lastName
    mobile
    registerNum
    subscribed
    verified
    avatar
    deliveryRequests(first: $first, after: $after, sort: $sort) {
      edges {
        node {
          id
          active
          status
          price
          travelAt
          createdAt
          updatedAt
          order {
            ...OrderFragment
          }
        }
      }
      pageInfo {
        hasNextPage
        hasPreviousPage
        startCursor
        endCursor
      }
      totalCount
    }
  }
}
