query GetOrdersMy(
  $ordersFirst: Int
  $after: String
  $sort: SortFilter = { field: "created_at", direction: desc }
) {
  me {
    id
    orders(first: $ordersFirst, after: $after, sort: $sort) {
      edges {
        node {
          ...OrderFragment
        }
        cursor
      }
      totalCount
      pageInfo {
        hasNextPage
        hasPreviousPage
        startCursor
        endCursor
      }
    }
  }
}
