query getOrders(
  $first: Int
  $after: String
  $filter: OrderFilter
  $sort: SortFilter = { field: "created_at", direction: desc }
) {
  orders(first: $first, after: $after, filter: $filter, sort: $sort) {
    edges {
      node {
        ...OrderFragment
      }
      cursor
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
    totalCount
  }
}
