query getSubscriptionPlans(
  $first: Int
  $after: String
  $filter: SubscriptionPlanFilter
  $sort: SortFilter = { field: "created_at", direction: asc }
) {
  subscriptionPlans(
    first: $first
    after: $after
    filter: $filter
    sort: $sort
  ) {
    edges {
      node {
        id
        name
        code
        price
        duration
        active
        startAt
        endAt
        preferences
        createdAt
        updatedAt
      }
      cursor
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
    totalCount
  }
}
