query getAddressDetail($id: ID!) {
  address(id: $id) {
    id
    name
    address1
    address2
    mobile
    email
    firstName
    lastName
    alternativeMobile
    alternativeEmail
    zipcode
    latitude
    longitude
    preferences
    country {
      id
      name
    }
    state {
      id
      name
    }
    district {
      id
      name
    }
    quarter {
      id
      name
    }
    location {
      id
      latitude
      longitude
    }
    sdq
    createdAt
    updatedAt
  }
}
