query GetMyTrucks {
  me {
    id
    trucks {
      id
      plateNumber
      serial
      weight
      netWeight
      importedDate
      mark
      model
      manufacturedDate
      taxon {
        id
        name
        code
        icon
        link
      }
      verified
      verifications {
        edges {
          node {
            id
            status
            comment
            field1
            field2
            field3
            field4
            field5
            createdAt
            updatedAt
          }
        }
      }
      createdAt
      updatedAt
    }
  }
}
