query GetMyTrucks {
  me {
    id
    trucks {
      id
      plateNumber
      serial
      weight
      netWeight
      importedDate
      manufacturedDate
      mark {
        id
        name
        code
      }
      model {
        id
        name
        code
        mark {
          id
          name
          code
        }
      }
      currentTrack {
        id
        latitude
        longitude
        createdAt
      }
      verified
      verifiedAt
      verifications {
        edges {
          cursor
          node {
            id
            status
            targetId
            targetType
            comment
            field1
            field2
            field3
            field4
            field5
            userId
            images
            imageObjects {
              id
              url
              fileName
              recordId
              recordType
            }
            user {
              id
              firstName
              lastName
              nickName
              mobile
              email
            }
            respondedBy {
              id
              firstName
              lastName
              nickName
              mobile
              email
            }
            createdAt
            updatedAt
          }
        }
        totalCount
        pageInfo {
          hasNextPage
          hasPreviousPage
          startCursor
          endCursor
        }
      }
      createdAt
      updatedAt
    }
  }
}
