query GetMyTrucks {
  me {
    id
    trucks {
      id
      plateNumber
      serial
      weight
      netWeight
      importedDate
      mark
      model
      manufacturedDate
      taxon {
        id
        name
        code
        icon
        link
      }
      verified
      verifiedAt
      verifications {
        edges {
          cursor
          node {
            id
            status
            comment
            field1
            field2
            field3
            field4
            field5
            # images
            # imageObjects {
            #   id
            #   url
            #   fileName
            #   recordId
            #   recordType
            # }
            createdAt
            updatedAt
          }
        }
        totalCount
        pageInfo {
          hasNextPage
          hasPreviousPage
          startCursor
          endCursor
        }
      }
      createdAt
      updatedAt
    }
  }
}
