query getOrder($number: String) {
  order(number: $number) {
    id
    number
    title
    status
    published
    my
    requested
    subscribed
    packageType
    packageWeight
    packageDimensions
    price
    carType
    carWeight
    senderName
    senderMobile
    receiverName
    receiverMobile
    travelAt
    travelDistance
    travelDuration
    audio
    video
    images
    imageObjects {
      id
      url
      fileName
      recordId
      recordType
    }
    origin {
      id
      address {
        id
        name
        address1
        address2
        latitude
        longitude
        country {
          id
          name
        }
        state {
          id
          name
        }
        district {
          id
          name
        }
        quarter {
          id
          name
        }
      }
    }
    destination {
      id
      address {
        id
        name
        address1
        address2
        latitude
        longitude
        country {
          id
          name
        }
        state {
          id
          name
        }
        district {
          id
          name
        }
        quarter {
          id
          name
        }
      }
    }
    user {
      id
      email
      firstName
      lastName
      mobile
      role
      isAdmin
    }
    deliveryRequests(first: 50) {
      edges {
        node {
          id
          price
          travelAt
          status
          user {
            id
            firstName
            lastName
            mobile
            email
            role
          }
          createdAt
          updatedAt
        }
      }
      totalCount
      pageInfo {
        hasNextPage
        hasPreviousPage
        startCursor
        endCursor
      }
    }
    createdAt
    updatedAt
  }
}
