query GetTruck($id: ID!) {
  truck(id: $id) {
    id
    plateNumber
    serial
    weight
    netWeight
    importedDate
    manufacturedDate
    user {
      id
      email
      firstName
      lastName
    }
    currentTrack {
      id
      latitude
      longitude
      createdAt
    }
    createdAt
    updatedAt
  }
}