query GetTaxons(
  $first: Int
  $after: String
  $before: String
  $last: Int
  $offset: Int
  $filter: TaxonFilter
  $sort: SortFilter
) {
  taxons(
    first: $first
    after: $after
    before: $before
    last: $last
    offset: $offset
    filter: $filter
    sort: $sort
  ) {
    edges {
      node {
        id
        code
        name
        link
        icon
        slug
        preferences
        hasChildren
        parentId
        parent {
          id
          code
          name
        }
        children {
          id
          code
          name
        }
        createdAt
        updatedAt
      }
      cursor
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
    totalCount
  }
}
