query GetUser {
  me {
    id
    firstName
    lastName
    mobile
    registerNum
    subscribed
    verified
    avatar
    verifications {
      edges {
        node {
          id
          status
        }
      }
    }
    trucks {
      id
      verified
      verifications {
        edges {
          node {
            id
            status
          }
        }
      }
    }
  }
}
