query GetVerifications(
  $first: Int
  $after: String
  $before: String
  $last: Int
  $offset: Int
) {
  verifications(
    first: $first
    after: $after
    before: $before
    last: $last
    offset: $offset
  ) {
    edges {
      cursor
      node {
        id
        status
        targetId
        targetType
        comment
        field1
        field2
        field3
        field4
        field5
        userId
        images
        imageObjects {
          id
          url
          fileName
          recordId
          recordType
        }
        user {
          id
          firstName
          lastName
          nickName
          mobile
          email
        }
        respondedBy {
          id
          firstName
          lastName
          nickName
          mobile
          email
        }
        createdAt
        updatedAt
      }
    }
    nodes {
      id
      status
      targetId
      targetType
    }
    totalCount
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
